export default function() {
	return [
		{
			url: "/gaming",
			icon: "gaming",
			title: "Gaming",
			dataFilter: 1,
			colMd: 4,
			imageSrc: "./images/gaming/drunkenstein/cover-image.png",
		},
		{
			url: "/web-design",
			icon: "web-design",
			title: "Web design",
			dataFilter: 2,
			colMd: 4,
			imageSrc: "./images/web-design/quizco/cover-image.png",
		},
		{
			url: "/branding-and-identity",
			icon: "branding-and-identity",
			title: "Branding & identity",
			dataFilter: 3,
			colMd: 4,
			imageSrc: "./images/branding-and-identity/krasi-stoyanov/cover-image.jpg",
		},
		{
			url: "/graphic-design",
			icon: "graphic-design",
			title: "graphic design",
			dataFilter: 4,
			colMd: 4,
			imageSrc: "./images/graphic-design/natured/cover-image.png",
		},
		// {
		// 	url: "/art-and-illustration",
		// 	icon: "art-and-illustration",
		// 	title: "Art & illustration",
		// 	dataFilter: 5,
		// 	colMd: 4,
		// 	imageSrc: "./images/art-and-illustration/space-cara.png",
		// },
		{
			url: "/literature",
			icon: "literature",
			title: "Literature",
			dataFilter: 6,
			colMd: 4,
			imageSrc: "./images/literature/art-of-loneliness.jpeg",
		},
		{
			url: "/photography",
			icon: "photography",
			title: "Photography",
			dataFilter: 7,
			colMd: 4,
			imageSrc: "./images/photography/botanic/cover-image.JPG",
		},
	];
}
